# Generated by Django 3.0.7 on 2021-06-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('standard', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2021, 6, 18))),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
